/**
 * status: "avaliando" | "favorita" | "descartada"
 */
window.LISTINGS = [
  {
    id: "48094852",
    nome: "Guarujá, Cond. na Mata Atlântica, 300m da Praia",
    local: "Balneário Praia do Pernambuco, Guarujá — SP",
    tipo: "Espaço inteiro · Casa",
    nota: 4.88,
    avaliacoes: 24,
    pessoas: 12,
    quartos: 4,
    camas: 10,
    banheiros: 2,
    periodo: "30/12/2026 – 02/01/2027",
    noites: 3,
    hospedesBusca: "10 adultos · 2 crianças",
    preco: "Consultar no Airbnb (Réveillon)",
    anfitria: "Silvia",
    checkin: "15:00 – 23:00",
    checkout: "até 12:00",
    foto: "https://a0.muscache.com/im/pictures/ff547d84-7817-4c49-be5c-021bf98b09a0.jpg?im_w=1200",
    fotos: [
      "https://a0.muscache.com/im/pictures/ff547d84-7817-4c49-be5c-021bf98b09a0.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/0432b850-33dc-4e3f-88ca-b09061a87b95.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/f7502287-fdf5-4a11-86b0-1f22fd778d28.jpg?im_w=720",
      "https://a0.muscache.com/im/pictures/78340d23-aec3-4c93-a22b-6eb818962e10.jpg?im_w=720",
    ],
    descricao:
      "Casa em condomínio, na melhor praia com águas claras e boa temperatura. Alto padrão com 3 quartos e 1 suíte com ar-condicionado e ventiladores. Casa ampla com belo jardim, churrasqueira e piscina. Cozinha com duas geladeiras e uma cervejeira. Home office com duas mesas e 2 monitores. 4 vagas de garagem. Condomínio exclusivo com portaria 24h e segurança total.",
    comodidades: [
      "Piscina privativa",
      "Acesso à praia compartilhado (300m)",
      "Churrasqueira a carvão",
      "Wi-Fi",
      "Ar-condicionado split",
      "Cozinha completa",
      "Estacionamento gratuito (4 vagas)",
      "Quintal privado cercado",
      "Pátio / varanda privativa",
      "Máquina de lavar",
      "HDTV com TV a cabo",
      "Itens básicos de praia",
      "Self check-in (fechadura inteligente)",
      "Vista para jardim, montanhas e piscina",
    ],
    regras: [
      "Máximo de 12 hóspedes",
      "Não são permitidos pets",
      "Não são permitidas festas ou eventos",
      "Proibido fumar",
      "Sem fotografia comercial",
      "Volume baixo após 22h",
    ],
    avaliacoesDetalhe: {
      limpeza: 4.75,
      comunicacao: 4.96,
      checkin: 4.96,
      precisao: 4.96,
      localizacao: 4.92,
      custoBeneficio: 4.83,
    },
    link: "https://www.airbnb.com.br/rooms/48094852?adults=10&check_in=2026-12-30&check_out=2027-01-02&children=2",
    status: "avaliando",
    notas: "",
  },
];
